#!/bin/sh

# latex compiler script
# usage : ./compile-latex <file-name>

name="${1%.tex}"

if [ $name == $1 ] ; then
    echo "'$1' is not a LaTeX file"
    exit 1
else
    pdflatex $name.tex && rm $name.log $name.aux
fi
