#!/bin/sh

# dmenu power control script
# usage : ./dmenu-powerctrl <font>

font="$1"
choices="poweroff\nreboot"
result=`echo -e "$choices" | dmenu -fn "$font" -p " "`

case "$result" in
    poweroff) poweroff ;;
    reboot) reboot ;;
esac
