#!/bin/sh

# dmenu power control script
# usage : ./dmenu-powerctrl <font>
# you are encouraged to change POWEROFF_CMD and REBOOT_CMD

POWEROFF_CMD=poweroff
REBOOT_CMD=reboot

font="$1"
choices="poweroff\nreboot"
result=`echo -e "$choices" | dmenu -fn "$font" -p "power control "`

case "$result" in
    poweroff) exec "$POWEROFF_CMD" ;;
    reboot) exec "$REBOOT_CMD" ;;
esac
