#!/bin/bash

# This is a dwm statusbar script

get_mem () {
    vmstat -sSM | awk '/total memory/{ t=$1 }
    /used memory/{ u=$1 }
    END{ printf "(ram %dM/%dM)\n", u, t; }'
}

get_bat () {
    BAT_PATH="/sys/class/power_supply/BAT0"
    bat_stat=$(cat "$BAT_PATH/status")
    bat_level=$(echo `cat "$BAT_PATH/energy_now"` `cat "$BAT_PATH/energy_full"` | awk '{print int($1/$2*100)}')

    case $bat_stat in
        Ch*)  stat="+ " ;;
        Dis*) stat="- " ;;
        *)    stat=""   ;;
    esac

    echo "(bat $stat${bat_level}%)"
}

get_vol () {
    mute=`pamixer --get-mute`
    if [ "$mute" == "true" ] ; then
        echo "(vol mute)"
    else
        vol_level=`pamixer --get-volume`
        echo "(vol ${vol_level}%)"
    fi
}

get_date () {
    echo `date +"([%H:%M] [%F] [%a])"`
}

get_wifi () {
    ssid="`iw wlp3s0 info | grep 'ssid' | sed 's/\sssid\s//'`"
    if [ ! -z "$ssid" ] ; then
        echo "(ssid [${ssid}]) "
    fi
}

while true
do
    xsetroot -name "`get_mem` `get_wifi``get_bat` `get_vol` `get_date`"
    sleep 1
done
